import test,{after,before} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createApp,canonicalLink} from '../server/app.mjs';
import {LANGUAGE_IDS} from '../server/languages.mjs';
const root=resolve(import.meta.dirname,'..'),catalog=JSON.parse(readFileSync(join(root,'lib/catalog.json'))),enhanced=JSON.parse(readFileSync(join(root,'lib/problems.json')));
let app,base,dir;
before(async()=>{dir=mkdtempSync(join(tmpdir(),'roshan-tests-'));app=createApp({dataDir:dir,staticDir:join(root,'dist'),catalog,enhanced});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${app.server.address().port}`;});
after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});
async function call(path,body,session={},origin=base){const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Origin:origin,Cookie:session.cookie||'','X-CSRF-Token':session.csrf||''},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();return {status:response.status,data,cookie:response.headers.get('set-cookie')?.split(';')[0]};}
async function account(username){const r=await call('/api/auth/register',{username,password:'correct-long-password'});assert.equal(r.status,201);return {cookie:r.cookie,csrf:r.data.csrfToken};}
test('catalog has 1000+ unique linked questions, levels, and core topics',()=>{assert.ok(catalog.length>=1000);assert.equal(new Set(catalog.map(p=>p.id)).size,catalog.length);assert.equal(new Set(catalog.map(p=>p.source)).size,catalog.length);for(const p of catalog){assert.ok(canonicalLink(p.source));assert.ok(['Easy','Medium','Hard'].includes(p.difficulty));assert.ok(p.topics.length);assert.ok(p.solutionSource.startsWith('https://github.com/doocs/leetcode/blob/'));}for(const topic of ['Array','String','Graph','Tree','Dynamic Programming','Binary Search','Linked List','Database'])assert.ok(catalog.some(p=>p.topics.includes(topic)));assert.equal(LANGUAGE_IDS.length,17);});
test('public browsing works and saved data requires an account',async()=>{assert.equal((await call('/api/questions')).status,200);assert.equal((await call('/api/auth/me')).data.user,null);assert.equal((await call('/api/practice')).status,401);const r=await fetch(base);assert.equal(r.status,200);assert.match(await r.text(),/Roshan code practice/);});
test('signup validation, password login, CSRF, isolation, and all-language persistence',async()=>{assert.equal((await call('/api/auth/register',{username:'!',password:'short'})).status,400);const a=await account('alice');const b=await account('bob');assert.equal((await call('/api/auth/login',{username:'alice',password:'wrong'})).status,401);assert.equal((await call('/api/practice',{action:'complete',problemId:'pivot-index',completed:true},{cookie:a.cookie})).status,403);assert.equal((await call('/api/practice',{action:'complete',problemId:'pivot-index',completed:true},a,'https://evil.example')).status,403);for(const language of LANGUAGE_IDS)assert.equal((await call('/api/practice',{action:'draft',problemId:'pivot-index',language,code:`private ${language}`},a)).status,200);assert.equal((await call('/api/practice',{action:'complete',problemId:'pivot-index',completed:true},a)).status,200);const state=(await call('/api/practice',undefined,a)).data;assert.equal(state.drafts.length,17);assert.equal(state.completions[0].completed,1);assert.deepEqual((await call('/api/practice',undefined,b)).data,{drafts:[],completions:[]});assert.equal((await call('/api/practice',{action:'draft',problemId:'invented',language:'python',code:''},a)).status,400);assert.equal((await call('/api/practice',{action:'complete',problemId:'pivot-index',completed:false},a)).status,200);assert.equal((await call('/api/practice',undefined,a)).data.completions[0].completed,0);const login=await call('/api/auth/login',{username:'ALICE',password:'correct-long-password'});assert.equal(login.status,200);assert.equal((await call('/api/practice',undefined,{cookie:login.cookie})).data.drafts.length,17);assert.equal((await call('/api/auth/logout',{},a)).status,200);assert.equal((await call('/api/practice',undefined,a)).status,401);});
test('accepted contributions award points atomically; duplicates earn nothing',async()=>{const a=await account('contributor');const description='Given an array of timestamps, find the longest interval where successive values differ by at most two. Input: [1,2,7]. Output: 2. Explain the approach and constraints.';const submission={title:'Timestamp quiet interval',difficulty:'Medium',topics:['Array'],description,source:''};assert.equal((await call('/api/questions',submission)).status,401);assert.equal((await call('/api/questions',{...submission,source:'javascript:alert(1)'},a)).status,400);const created=await call('/api/questions',submission,a);assert.equal(created.status,201);assert.equal(created.data.pointsEarned,10);assert.equal(created.data.user.points,10);assert.equal((await call('/api/questions',submission,a)).status,409);assert.equal((await call('/api/auth/me',undefined,a)).data.user.points,10);assert.equal((await call('/api/questions',{...submission,title:'Different duplicate name',source:catalog[0].source},a)).status,409);assert.equal((await call('/api/questions',{...submission,title:catalog[0].title},a)).status,409);const [r1,r2]=await Promise.all([call('/api/questions',{...submission,title:'Unique parallel interval'},a),call('/api/questions',{...submission,title:'Unique parallel interval'},a)]);assert.deepEqual([r1.status,r2.status].sort(),[201,409]);assert.equal((await call('/api/auth/me',undefined,a)).data.user.points,20);assert.equal((await call('/api/practice',{action:'complete',problemId:created.data.question.id,completed:true},a)).status,200);for(let i=0;i<3;i++)assert.equal((await call('/api/questions',{...submission,title:'Useful original exercise '+i},a)).status,201);assert.equal((await call('/api/questions',{...submission,title:'Useful original exercise six'},a)).status,429);const questions=(await call('/api/questions')).data.questions;assert.ok(questions.some(p=>p.id===created.data.question.id&&p.contributor==='contributor'));});
test('passwords and session credentials are not stored in plaintext',()=>{const u=app.db.prepare('SELECT * FROM users WHERE username=?').get('alice');assert.notEqual(u.hash,'correct-long-password');assert.equal(u.hash.length,128);const token=app.db.prepare('SELECT token_hash FROM sessions LIMIT 1').get();assert.equal(token.token_hash.length,64);});
test('LeetCode URL normalization rejects unsafe hosts and preserves canonical problems',()=>{assert.equal(canonicalLink('https://leetcode.com/problems/two-sum/description/?x=1'),'https://leetcode.com/problems/two-sum/');for(const u of ['https://evil.com/problems/two-sum/','http://leetcode.com/problems/two-sum/','https://leetcode.com.evil.com/problems/two-sum/','https://a:pw@leetcode.com/problems/two-sum/'])assert.equal(canonicalLink(u),null);});
test('full phone keypad scenario is public and unknown questions cannot trigger arbitrary fetches',async()=>{const r=await call('/api/problems/lc-17/statement');assert.equal(r.status,200);assert.equal(r.data.statement.examples.length,3);assert.ok(JSON.stringify(r.data.statement.description).includes('telephone keypad'));assert.equal((await call('/api/problems/lc-999999/statement')).status,404);assert.equal((await call('/api/problems/https%3A%2F%2Fevil.example/statement')).status,404);});
